apply additional amplitude event
Team-Smeme/smeem-aos pull request #310
Opened 2024-05-25 11:02 UTC by daehwan2da

- closed #issue number

## *⛳️ Work Description*
- task1
- task2
- task3

## *📸 Screenshot*

## *📢 To Reviewers*
-

2024-05-25 12:01 UTC, taeheeL requested changes
리뷰 확인해주세요~

2024-05-25 12:01 UTC, haeti-dev commented on app/src/main/java/com/sopt/smeem/presentation/mypage/mysummary/MySummaryScreen.kt
>      }
영역을 따로 만들어야 될 것 같습니다 isDataChanged가 true 되는 상황이 트레이닝 플랜을 변경했을때 뿐이라 scope를 분리해주는게 좋을 것 같아요~
```suggestion
        LaunchedEffect(true) {
            eventVM.sendEvent(AmplitudeEventType.ACHIEVEMENT_VIEW)
        }
    }
```

2024-05-25 12:01 UTC, taeheeL commented on app/src/main/java/com/sopt/smeem/presentation/mypage/mysummary/MySummaryScreen.kt
>  ) {
```suggestion
fun MySummaryScreen(
    navController: NavController,
    viewModel: MySummaryViewModel,
    eventVM: EventVM = hiltViewModel(),
    modifier: Modifier = Modifier
) {
```

이렇게 안하면 빌드 안되지 않나요?

2024-05-26 07:36 UTC, daehwan2da commented on app/src/main/java/com/sopt/smeem/presentation/mypage/mysummary/MySummaryScreen.kt
>      }
반영했아요

2024-05-26 07:38 UTC, daehwan2da commented on app/src/main/java/com/sopt/smeem/presentation/mypage/mysummary/MySummaryScreen.kt
>  ) {
반영햇아요

2024-05-26 10:16 UTC, taeheeL approved these changes
고생했어유~

2024-05-26 15:31 UTC, merged