#54 드르륵 바텀시트랑 연동
Team-Smeme/smeem-aos pull request #63
Opened 2023-07-03 13:47 UTC by taeheeL

- #54

2023-07-06 08:37 UTC, daehwan2da requested changes

2023-07-06 08:37 UTC, daehwan2da commented on app/src/main/java/com/sopt/smeem/calendar/CalendarActivity.kt
> +                when (newState) {
로깅용 분기 제거 부탁드리겠습니다

2023-07-06 08:37 UTC, daehwan2da commented on app/src/main/java/com/sopt/smeem/calendar/MonthActivity.kt
불필요한 Activity 인것같습니다. 제거 부탁드릴게요~
(코드 유지를 의도하신바라면, 설명좀 부탁드리겠습니다)

2023-07-06 08:37 UTC, daehwan2da commented on app/src/main/res/layout/activity_month.xml
MonthActivity 와 같이 해당 xml 도 제거 요청드립니다

2023-07-06 08:37 UTC, daehwan2da commented on app/src/main/java/com/sopt/smeem/calendar/WeekActivity.kt
해당 클래스 사용처가 없는 것 같아 제거 부탁드리겠습니다
(코드 유지가 의도하신바라면, 설명 부탁드리겠습니다~)

2023-07-06 08:37 UTC, daehwan2da commented on app/src/main/res/layout/activity_week.xml
WeekActivity 와 같이 제거 요청 부탁드리겠습니다.

2023-07-06 08:37 UTC, daehwan2da commented on app/src/main/java/com/sopt/smeem/calendar/IntegratedCalendar.kt
> +    private lateinit var dividerView: View
```suggestion
    val monthlyCalendar: MonthlyCalendar
    val weeklyCalendar: WeeklyCalendar
    val handleView: View
    val dividerView: View
```

2023-07-06 08:37 UTC, daehwan2da commented on app/src/main/res/layout/activity_calendar.xml
> +            android:id="@+id/cl_calendar"
캘린더 내용을 담았다기 보다는, Home 에서 Top 쪽에 고정되는 레이아웃을 정의해둔 역할을 하는 layout 인 네이밍으로 정의하면 좋을것같습니다~

```suggestion
            android:id="@+id/layout_home_top"
```

2023-07-06 08:37 UTC, daehwan2da commented on app/src/main/java/com/sopt/smeem/calendar/CalendarActivity.kt
> +        var isTopSheetInitiatedEvent = false
제거해도 괜찮을것같습니다

2023-07-06 08:37 UTC, daehwan2da commented on app/src/main/java/com/sopt/smeem/calendar/CalendarActivity.kt
> +        topSheetBehavior.setPeekHeight(168.dp(this))
이렇게 세팅되면 기기대응은 어렵겠군요.. 이후 추가 대응이 필요할것같네요
TODO 에 올려두고 이후 새로운 task 로 작업들어가면 좋을것같습니다~
- #62

2023-07-06 08:37 UTC, daehwan2da commented on app/src/main/res/layout/calendar_top_sheet.xml
해당 파일 제거해도 괜찮을것같습니다

2023-07-06 08:37 UTC, daehwan2da commented on app/src/main/res/layout/top_sheet.xml
해당 파일 제거해도 괜찮을것같습니다.

2023-07-06 08:37 UTC, daehwan2da commented on app/src/main/res/layout/view_calendar_week_descripton.xml
해당 파일 제거해도 괜찮을것같습니다.

2023-07-06 08:37 UTC, daehwan2da commented on app/src/main/res/layout/view_monthly_calendar_day.xml
> +        android:layout_marginVertical="7dp"
`marginVertical=7dp`
제거해도 영향이 없는것같습니다

2023-07-06 08:37 UTC, daehwan2da commented on app/src/main/res/layout/activity_calendar.xml
> +            <!--            <androidx.constraintlayout.widget.ConstraintLayout-->
불필요 주석 제거 부탁드립니다~

2023-07-06 08:37 UTC, daehwan2da commented on app/src/main/res/layout/activity_calendar.xml
> +        <androidx.coordinatorlayout.widget.CoordinatorLayout
의도하신게 S M T W ,,, 와 캘린더 셀들간의 간격 7dp 라면, 
Calendar Sheet 를 wrapping 하는 CoordinatorLayout 에 `android:layout_marginTop="7dp"` 적용하면,
view_monthly_calendar_day.xml 의 CoordinatorLayout 에서 7dp margin,  padding 준거 제거 가능할것같습니다.

2023-07-06 08:37 UTC, daehwan2da commented on app/src/main/res/layout/view_monthly_calendar_day.xml
> +        android:paddingVertical="7dp">
의도하신게 S M T W ,,, 와 캘린더 셀들간의 간격 7dp 라면, 
activity_calendar 에서 Calendar Sheet 를 wrapping 하는 CoordinatorLayout 에 `android:layout_marginTop="7dp"` 적용하면,
view_monthly_calendar_day.xml 의 CoordinatorLayout 에서 7dp margin,  padding 준거 제거 가능할것같습니다.

2023-07-06 08:37 UTC, daehwan2da commented on app/src/main/res/layout/view_monthly_calendar_day.xml
> +        android:paddingVertical="7dp">
padding 7dp 의 경우 디스플레이에 따라 아래 바텀시트의 공간이 작아져 노출이 되지 않을 수 있어서요, 오히려 padding 은 제거해 아래 뷰를 보장해주는 방향이 좋을것같습니다.
<img width="362" alt="스크린샷 2023-07-06 오전 1 19 41" src="https://github.com/Team-Smeme/smeem-aos/assets/88091704/fe23c478-2b0f-42f7-bd24-055c539ff014">

2023-07-06 08:37 UTC, daehwan2da commented on app/src/main/java/com/sopt/smeem/calendar/CalendarActivity.kt
> +                when (newState) {
# Before

https://github.com/Team-Smeme/smeem-aos/assets/88091704/eb99c2a5-24d9-427f-920e-5b4d21955bda


- 월캘린더가 펼쳐질때 주캘린더의 위치가 잔상으로 남아 핸들과 월캘린더 사이의 간격 (주캘린더 간격)이 유지된다.

# After

https://github.com/Team-Smeme/smeem-aos/assets/88091704/e8e05608-30ae-4862-ac0a-7bce0761eed2



- 주캘린더의 visibility 를 슬라이딩 state 에 맞춰 조절해 월캘린더와 독립적으로 간격을 유지하도록 변경한다.
- 코드 변경 필요

#### on CalendarActivity
``` kotlin
        topSheetBehavior.setTopSheetCallback(object : TopSheetCallback() {
            override fun onStateChanged(topSheet: View, newState: Int) {
                when (newState) {
                    TopSheetBehavior.STATE_EXPANDED -> {
                        weeklyCalendar.visibility = GONE
                        monthlyCalendar.visibility = VISIBLE
                    }

                    TopSheetBehavior.STATE_COLLAPSED -> {
                        monthlyCalendar.visibility = INVISIBLE
                        weeklyCalendar.visibility = VISIBLE
                    }

                    TopSheetBehavior.STATE_DRAGGING -> {
                        weeklyCalendar.visibility = VISIBLE
                        monthlyCalendar.visibility = VISIBLE
                    }

                    TopSheetBehavior.STATE_SETTLING -> {
                        weeklyCalendar.visibility = GONE
                    }
                }
            }

            override fun onSlide(topSheet: View, slideOffset: Float) {
                weeklyCalendar.verticalSliding(slideOffset)

                val bottomSheetOffset = bottomSheet.height * slideOffset
                bottomSheet.y = bottomSheetOffset

            }

        })
```

#### on WeeklyCalendar 확장 함수 추가
``` kotlin
fun WeeklyCalendar.verticalSliding(topSheetSlideOffset: Float) {
    if (topSheetSlideOffset in 0.0f..1.0f) {
        this.alpha = 1 - topSheetSlideOffset
    }
    isEnabled = topSheetSlideOffset != 1.0f
    isClickable = topSheetSlideOffset != 1.0f

    if (topSheetSlideOffset > alpha) { // down sliding
        this.visibility = View.GONE
    }
}
```

위와 같이 확장함수 정의하고,

2023-07-07 08:53 UTC, taeheeL commented on app/src/main/res/layout/activity_week.xml
실험용 쥐가 같이 들어갔네요 ㅎㅎ 제거 했슴다

2023-07-07 09:03 UTC, taeheeL commented on app/src/main/res/layout/activity_calendar.xml
> +            <!--            <androidx.constraintlayout.widget.ConstraintLayout-->
이거 나중에 써야해서 일단은 남길게요!

2023-07-08 08:38 UTC, merged